Fs=42;Ts=1/Fs;
 t=-1:Ts:40*Ts-Ts;
a = 0:478;
 f=5;
%y=sinc(pi*t*f);
x = 3*Num;
figure;
plot(a,x);
xlabel('x');
ylabel(' magnitude');
 N=512;
fy=(fft(x,N));
figure;
fr=(0:N-1)*Fs/N;
 %fy=fy(1:floor(end/2));
 %fr=fr(1:floor(end/2));
 plot(fr,fftshift(abs(fy)));
 xlabel(' frequency x^{-1}');
 ylabel(' magnitude');